development:
  forest_env_secret: 62cf87322bd3a86b4dd62164dc8f5c36e86f3a0fbfbdc155a1ca1cf862f14242
  forest_auth_secret: qj5n3XjJm8n4XK5paMmJ5A
  forest_application_url: http://localhost:3000
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
production:
  forest_env_secret: beb05e08b195bd99bdbae0e4f4d9997d3a262ad81ddcd5fd17062ec44308b6af
  forest_auth_secret: 8bac51c94a657649ec1f3b857652c79455332379b1faaf17
  forest_application_url: https://berk-overflow.herokuapp.com/
